config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    root 'home#top'

    resources :users

    # ネストにすることで/competitions/1/entries/newとかができる
    resources :competitions do
        resources :entries, only: [:new, :create, :edit, :update, :destroy]
    end
get "/youtube" => "youtube#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competition.rb
class Competition < ApplicationRecord
    # オブジェクトがDBに保存される前のバリデーション
    # presence:出席 → 空でないこと
    validates :title, :competition_event, :period_start, :period_end, presence: true

    validate :start_end_check

    # 大会期間の日付の前後を検証
    def start_end_check
        errors.add(:period_end, "の日付を正しく記入してください。") if
            # period_end,startに値が入っていて、なおかつ、startがend以前である場合
            period_start && period_end && period_start > period_end
    end

    has_many :entries

end

app/models/entry.rb
class Entry < ApplicationRecord
    # carrierwaveの設定
    # アップロードファイル名が格納されるDBのカラム名とアップロードクラスを紐付ける
    mount_uploader :video, VideoUploader

    belongs_to :competition
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # database_authenticatable → DBに保存されたパスが正しいか検証。パスの暗号化も行う
  # registerable → 登録処理を通してサインアップ機能
  # recoverable → パスワードをリセットする
  # rememberable → 保存されたcookieからユーザーを記憶するトークンを作成
  # validatable → Emailやパスワードのバリデーションを追加する
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # CSRF対策
    # Railsで生成されるすべてのフォームとAjaxリクエストにセキュリティトークンが自動的に含まれる
    # htmlとcookiesのセキュリティトークンがマッチしない場合には例外がスローされる。
    protect_from_forgery with: :exception

    # devise_controller?とはdeviseを生成したときにできるヘルパーメソッド
    # if: :devise_controller でdeviseにまつわる画面に遷移したときに ということ
    # こうすることですべての画面で:configure_permitted_parametersするのを防ぐ
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    # devise版のストロングパラメータ
    # added_attrsで保存できる項目を設定
    # そのadded_attrsを使ってdeviseの3つのアクションのキーに設定する
    def configure_permitted_parameters
        added_attrs = [ :email, :username, :password, :password_confirmation ]
        devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
        devise_parameter_sanitizer.permit :account_update, keys: added_attrs
        devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
    # ヘルパーを読み込む
    include CompetitionsHelper
    # 各アクションを実行する前にset_competitionメソッドを実行
    # %i[]でシンボルの配列を作り出せる
    before_action :set_competition, only: %i[show edit update destroy]

    def index
        # ここでこの開催期間が今日以前であれば、 "開催前" 、含んでいれば "開催中" 、過ぎていれば "結果をみる"
        sorted_competitions =
            "SELECT *,
                    CASE
                        WHEN period_start > now() THEN 2
                        WHEN period_start <= now() && now() <= period_end THEN 1
                        WHEN period_end < now() THEN 3
                        ELSE 4
                    END AS status
            FROM competitions
            ORDER BY status ASC, period_end ASC;"

        @sorted_competitions = ActiveRecord::Base.connection.select_all(sorted_competitions).to_ary
    end

    def new
        # Competitionオブジェクトを作成して@competitionに格納
        @competition = Competition.new
    end

    def create
        # 今回はDBへの保存を一括で行うcreateを使うのではなく、
        # saveする際の挙動を場合分けしたいため　オブジェクトの生成(new)→保存(save)の二段階
        @competition = Competition.new(competition_params)

        if @competition.save
            # bootstrapのflashを表示させる
            redirect_to '/competitions', flash: {success: "登録が完了しました"}
        else
            flash.now[:danger] = '登録が失敗しました'
            render '/competitions/new'
        end
    end

    # competitionの詳細（ランキング画面）
    def show
        # competition_helperにカスタムヘルパーを設定
        light_entries = entries(3)
        @light_entries = ActiveRecord::Base.connection.select_all(light_entries).to_ary

        middle_entries = entries(6)
        @middle_entries = ActiveRecord::Base.connection.select_all(middle_entries).to_ary

        heavy_entries = entries(9)
        @heavy_entries = ActiveRecord::Base.connection.select_all(heavy_entries).to_ary
    end

    def edit
    end

    def update

        if @competition.update(competition_params)
            # bootstrapのflashを表示させる
            redirect_to @competition, flash: {success: "編集内容を保存しました"}
        else
            flash.now[:danger] = '登録が失敗しました'
            render 'edit'
        end
    end

    def destroy
        @competition.destroy
        redirect_to '/competitions', flash: {success: "削除が完了しました"}
    end


    private

    # strong parameters
    # 入力者から受け取る項目をcompeition_paramsに定義
    def competition_params
        params.require(:competition).permit(:title, :competition_event, :period_start, :period_end)
    end

    # require()の引数はform_withで指定したモデル名
    def set_competition
        @competition = Competition.find(params[:id])
    end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    before_action :set_competition, only: %i[new]

    def new
        @entry = Entry.new
    end

    def create
        # paramsに入っているcompetition_idを取り出す
        @competition_id = Competition.find(params[:competition_id]).id

        @entry = Entry.new(entry_class: entry_params[:entry_class],
                           lifted_weight: entry_params[:lifted_weight],
                           video: entry_params[:video],
                           competition_id: @competition_id,
                           user_id: current_user.id)

        if @entry.save
            # bootstrapのflashを表示させる
            redirect_to "/competitions/#{@competition_id}", flash: {success: "登録が完了しました"}
        else
            flash.now[:danger] = '登録が失敗しました'
            render '/entries/new'
        end
    end

    # form_withでモデル指定でなく、url指定した場合はrequireオプションはいらない
    def entry_params
        params.permit(:entry_class, :lifted_weight, :video)
    end

    # paramsの中のcompetition_idに入っている値のみを取り出す
    def set_competition
        @competition = Competition.find(params[:competition_id])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/youtube_controller.rb
class YoutubeController < ApplicationController
    require 'google/apis/youtube_v3'
    GOOGLE_API_KEY = Rails.application.credentials.google[:api_key]

    def find_videos(keyword, after: 1.months.ago, before: Time.now)
        # 今回はGoogleAPIのYouTubeV3のYouTubeServiceのクラスを新規作成して、serviceに格納する
        # このYouTubeServiceは動画のアップロード、プレイリストの作成と管理、コンテンツの検索など、YouTubeのコア機能をサポート
        service = Google::Apis::YoutubeV3::YouTubeService.new
        service.key = GOOGLE_API_KEY

        next_page_token = nil

        options = {
            # キーワード検索を行うためqをキーにする.動画を検索したいためtypeをvideoにしている
            q: keyword,
            type: 'video',
            max_results: 3,
            order: :date,
            # 検索結果がmax_results以上である場合に、検索結果の中に入っている.検索した結果、次のページへ行くときに渡すトークン
            page_token: next_page_token,
            # published_にはRFC3339形式の日時の値を入れる必要があるため、iso8601メソッドで変換。
            published_after: after.iso8601,
            published_before: before.iso8601
        }

        # YouTubeServiceにはlist_〇〇メソッドが用意されている
        # list_〇〇〇(part名, デフォルトのnilから変更したいオプションキー)
        # 今回のpartパラメータは:snippetで、その値はopt
        # :snippetは複数オプションを指定したいときに使う
        service.list_searches(:snippet, options)
    end

    def index
        @youtube_data = find_videos('engineer')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
    def entries(entry_class)
            "SELECT *,RANK() OVER (PARTITION BY entries.entry_class ORDER BY entries.lifted_weight DESC) AS rnk
                FROM (
                    SELECT entries.*,users.username
                        FROM entries
                            INNER JOIN users ON users.id = entries.user_id
                        WHERE entries.competition_id = #{@competition.id}
                            AND entries.entry_class = #{entry_class}
                ORDER BY entries.lifted_weight DESC, entries.updated_at
            ) AS t"
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/youtube_helper.rb
module YoutubeHelper
end

app/views/competitions/_competition_form.html.erb
<% #renderで画面遷移する際のflashが動作させるために,local: trueオプションを付する %>
<% #local: trueがない場合、Rails5ではAjaxによる送信という意味になる。 %>
<% #普通にHTMLとしてフォームを送信する場合にlocal: trueが必要になる %>
<%= form_with(model: @competition, local: true) do |f| %>

  <div class="row">
    <div class="input">

      <div class="form-group row">
        <%= f.label(:title, ("大会名")) %>
        <%= f.text_field :title, class: "form-control", placeholder: "ベンチプレス大会" %>
      </div>

      <div class="form-group row">
        <%= f.label(:competition_event, ("種目")) %>
        <%= f.text_field :competition_event, class: "form-control", placeholder: "ペンチプレス" %>
      </div>

      <div class="form-group row">
        <%= f.label(:period_start, ("大会始期")) %>
        <%= f.date_field :period_start, class: "form-control" %>
      </div>

      <div class="form-group row">
        <%= f.label(:period_end, ("大会終期")) %>
        <%= f.date_field :period_end, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group row save">
    <%= f.submit submit_label, class: "btn btn-primary" %>
  </div>

<% end %>

app/views/competitions/_competition_info.html.erb
<div class="competition-info">
  <h4 class="card-title"><%= competition["title"] %></h4>
  <p class="card-text">開催期間<%= competition["period_start"] %>〜<%= competition["period_end"] %></p>
  <div class="champions">
    <p class="title">Champions</p>

    <p class="col-sm-5">ライト級</p>
    <p class="col-sm-4">name</p>
    <p class="col-sm-3">100kg</p>

    <p class="col-sm-5">ミドル級</p>
    <p class="col-sm-4">name</p>
    <p class="col-sm-3">100kg</p>

    <p class="col-sm-5">ヘビー級</p>
    <p class="col-sm-4">name</p>
    <p class="col-sm-3">100kg</p>
  </div>
</div>

app/views/competitions/_competition_rank.html.erb
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th class="col-sm-2">順位</th>
    <th class="col-sm-3">重量</th>
    <th class="col-sm-3">名前</th>
    <th class="col-sm-4">ムービー</th>
  </tr>
  </thead>
  <% entries.each do |entry| %>
    <tbody>
    <tr>
      <th scope="row"><%= entry["rnk"] %></th>
      <td><%= entry["lifted_weight"] %></td>
      <td><%= entry["username"] %></td>
      <td>
        <%= video_tag("/uploads/entry/video/#{entry["id"]}/#{entry["video"]}",
                      :controls => true,
                      :loop => false,
                      :size => 10 * 10)
        %>
      </td>
    </tr>
    </tbody>
  <% end %>
</table>

app/views/competitions/_error_message.html.erb
<div class="error-message">
  <% if competition.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% competition.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/competitions/edit.html.erb
<div class="container competitions-edit">

  <div class="col-sm-12 back">
    <a href="/competitions/<%= @competition.id %>" class="btn">大会詳細へもどる</a>
  </div>

  <h1>大会を編集する</h1>
  <div class="delete-button">
    <%= link_to 'この大会を削除する', "/competitions/#{@competition.id}",
                method: :delete,
                class: "btn btn-danger",
                data: {confirm: '本当に削除しますか？',
                       cancel: 'やめる',
                       commit: '大会を削除する'}, title: '削除の確認'
    %>
  </div>
  <%= render partial: 'error_message', locals: {competition: @competition} %>
  <%= render partial: 'competition_form', locals: {submit_label: '編集内容を保存する'} %>

</div>

app/views/competitions/index.html.erb
<h1>大会一覧</h1>
<div class="container competition-index">

  <div class="col-sm-12 new">
    <a href="/competitions/new" class="btn btn-primary">大会新規作成</a>
  </div>

  <% @sorted_competitions.each do |competition| %>
    <div class="col-sm-4">
      <% if competition["status"] == 2 %>

        <div
          class="card"
          style="background:lightblue"
        >
          <div class="card-body">

            <% # locals: {competition: competition}を使うことで %>
            <% # competition(後者)をテンプレート先へcompetition(前者)という名前で渡す %>
            <%= render partial: 'competition_info', locals: {competition: competition} %>
            <a href="/competitions/<%= competition["id"] %>"
               class="btn btn">
              開催前
            </a>
          </div>
        </div>

      <% elsif competition["status"] == 1 %>

        <div class="card">
          <div class="card-body">
            <%= render partial: 'competition_info', locals: {competition: competition} %>
            <a href="/competitions/<%= competition["id"] %>"
               class="btn btn-warning"
            >
              開催中
            </a>
          </div>
        </div>

      <% else %>

        <div
          class="card"
          style="background:lightgray"
        >
          <div class="card-body">
            <%= render partial: 'competition_info', locals: {competition: competition} %>
            <a href="/competitions/<%= competition["id"] %>"
               class="btn btn-success"
            >
              結果をみる
            </a>
          </div>
        </div>
      <% end %>

    </div>
  <% end %>
</div>

app/views/competitions/new.html.erb
<div class="container competition-new">

  <div class="col-sm-12 back">
    <a href="/competitions/" class="btn">大会一覧へもどる</a>
  </div>

  <h1>大会を新規作成する</h1>
  <%= render partial: 'error_message', locals: {competition: @competition} %>
  <%= render partial: 'competition_form', locals: {submit_label: '新規作成する'} %>
</div>

app/views/competitions/show.html.erb
<div class="container competition-show">
  <div class="col-sm-4">
    <div class="backindex">
      <a href="/competitions" class="btn">大会一覧にもどる</a>
    </div>
  </div>
  <div class="col-sm-8">
    <div class="entry">
      <a href="/competitions/<%= @competition.id %>/entries/new" class="btn btn-primary">この大会にエントリーする</a>
    </div>
  </div>
  <div class="col-sm-12 edit">
    <a href="/competitions/<%= @competition.id %>/edit" class="btn btn-warning">この大会を編集する</a>
  </div>

  <h1><%= @competition.title %></h1>
  <h2>開催期間 <%= @competition.period_start %> 〜 <%= @competition.period_end %></h2>

  <% # navでナビゲーションコンポーネントを利用,nav-tabsで横並びのタブにする（2つとも必要） %>
  <ul class="nav nav-tabs">
    <% # aタグとそれぞれのタブの内容を紐付ける %>
    <% # data-toggle="tab"はタブの切替機能を有効にするために必要 %>
    <% # class="active"で画面遷移時のタブ選択する %>
    <li class="active"><a href="#right" data-toggle="tab">ライト級</a></li>
    <li><a href="#middle" data-toggle="tab">ミドル級</a></li>
    <li><a href="#heavy" data-toggle="tab">ヘビー級</a></li>
  </ul>
  <div class="tab-content">

    <% # 選択中のタブの中身のみを表示させるようにtab-paneを指定（これがないとタブ関係なくすべての内容が一斉にでてくる） %>
    <% # タブと同様,クラスにactiveを指定して画面遷移時にこのコンテンツを表示させる %>
    <div class="tab-pane active" id="right">
      <%= render partial: 'competition_rank', locals: {entries: @light_entries} %>
    </div>

    <div class="tab-pane" id="middle">
      <%= render partial: 'competition_rank', locals: {entries: @middle_entries} %>
    </div>

    <div class="tab-pane" id="heavy">
      <%= render partial: 'competition_rank', locals: {entries: @heavy_entries} %>
    </div>

  </div>

</div>

app/views/entries/new.html.erb
<div class="container competitions-entry">

  <div class="col-sm-12 back">
    <a href="/competitions/1" class="btn">大会詳細（ランキング画面）へもどる</a>
  </div>

  <h1><%= @competition.title %></h1>
  <% # modelオプションで@entryにしたときパスエラーが発生した
     # urlオプションでgetかpostかどちらかのパスは指定することができたが、両方に指定することはできなかった）
     # modelオプションを削除して、urlでcompetition_entriesパス（post先）を指定
  %>
  <%= form_with(url: competition_entries_path, local: true,html: {multipart: true, class: "dropzone"}) do |f| %>
    <div class="row">
      <div class="input">

        <div class="form-group row">
          <%= f.label(:entry_class, ("階級")) %>
          <%= f.select :entry_class, [["ライト級", 3], ["ミドル級", 6], ["ヘビー級", 9]], class: "form-control", placeholder: "ベンチプレス大会" %>
        </div>

        <div class="form-group row">
          <%= f.label(:lifted_weight, ("1RM重量")) %>
          <%= f.text_field :lifted_weight, class: "form-control", placeholder: "1RMの重量を入力" %>
        </div>

        <div class="form-group row">
          <div class="field">
            <%= f.label :video %>
            <% #htmlのaccept属性により、動画のみを許容する %>
            <%= f.file_field :video, :accept => 'video/*' %>
          </div>
        </div>

      </div>
    </div>

    <div class="form-group row save">
      <%= f.submit "エントリーする", class: "btn btn-primary" %>
    </div>

  <% end %>

</div>

app/views/home/top.html.erb
<div class="top-full">
  <p class="toppage-p">オンラインワークアウトコンペティションを開催しています</p>
  <div class="a-wrapper">
    <%= link_to "現在開催中の大会を見る", '/competitions', class: "btn btn-lg btn-warning" %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% #flashはハッシュ形式であるためeachメソッドが使える %>
<% flash.each do |key, value| %>
  <p class="alert alert-<%= key %>">
    <%= value %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p class="footer-p">© 2021 Workout Competition</p>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Workout Competition", '/', id: "logo" %>

    <nav>
      <ul class="nav navbar-nav navbar-right header-ul">
        <li class="balloon">
          <p>エントリーしている大会があります</p>
        <li class="character-wrapper">
          <img src="/images/character.png">
        </li>
        </li>


        <li><%= link_to "大会", '/competitions' %></li>

        <% if user_signed_in? %>
          <li><%= link_to 'マイステータス', '#' %></li>
          <li><%= link_to '統計情報', '#' %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'サインアップ', new_user_registration_path %></li>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutCompetition</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<%= render 'layouts/header' %>
<%= render 'layouts/flash' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/users/edit.html.erb
<div class="container user-edit">

  <div class="col-sm-12 edit">
    <a href="/users/1" class="btn">マイステータスにもどる</a>
  </div>

  <h1>〇〇さんのステータスを編集する</h1>

  <form>
    <div class="row">
      <div class="col-sm-6 edit-image">

        <div class="avatar-wrapper">
          <img src="/images/monster.jpeg" width="200px" height="200px">
        </div>

        <div>
          <p>プロフィール画像を変更する</p>
        </div>

        <div class="dropzone">
          <p>ファイルをここにドロップするか</p>
          <p>ここをクリックしてください</p>
        </div>

      </div>

      <div class="col-sm-6">

        <div class="form-group row status-edit">
          <label for="text">名前</label>
          <div>
            <input type="text" class="form-control" placeholder="名前">
          </div>
        </div>

        <div class="form-group row range">
          <label for="formControlRange">身長</label>
          <input type="range" class="form-control-range" id="formControlRange">
        </div>

        <div class="form-group row range">
          <label for="formControlRange">体重</label>
          <input type="range" class="form-control-range" id="formControlRange">
        </div>

      </div>
    </div>

    <div class="form-group row edit-save">
      <div class="col-sm-12">
        <button type="submit" class="btn btn-primary">編集内容を保存する</button>
      </div>
    </div>

  </form>

</div>

app/views/users/index.html.erb
<div class="container user-index">

  <h1>ユーザー一覧</h1>

  <form>
    <div class="search-group">
      <div class="row">

        <div class="form-group row col-sm-3">
          <label for="text">名前</label>
          <div>
            <input type="text" class="form-control" placeholder="名前">
          </div>
        </div>

        <div class="form-group row col-sm-4">
          <label for="text">メールアドレス</label>
          <div>
            <input type="text" class="form-control" placeholder="メールアドレス">
          </div>
        </div>

        <div class="form-group row col-sm-1">
          <label for="text">階級</label>
          <div>
            <select name="class" id="class">
              <option value="right">ライト級</option>
              <option value="middle">ミドル級</option>
              <option value="heavy">ヘビー級</option>
            </select>
          </div>
        </div>

        <div class="form-group row col-sm-4 entry-competition-form">
          <label for="text">エントリーした大会</label>
          <div>
            <select name="entry_competition" id="entry_competition">
              <option value="ベンチプレスNO.1大会">ベンチプレスNO.1大会</option>
              <option value="スクワットNO.1大会">スクワットNO.1大会</option>
              <option value="デッドリフトNO.1大会">デッドリフトNO.1大会</option>
            </select>
          </div>
        </div>

      </div>
      <div class="form-group row search">
        <div class="col-sm-12">
          <button type="submit" class="btn btn-primary">検索</button>
        </div>
      </div>
    </div>
  </form>


  <form>
    <div class="col-sm-12 delete">
      <a href="#" class="btn btn-danger">チェックをつけたユーザーを削除する</a>
    </div>

    <table class="table table-striped table-hover">

      <thead>
      <tr>
        <th class="col-sm-2"></th>
        <th class="col-sm-3">id</th>
        <th class="col-sm-3">名前</th>
        <th class="col-sm-4">メールアドレス</th>
      </tr>
      </thead>

      <tbody>
      <tr>
        <th scope="row form-check">
          <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
        </th>
        <td>33</td>
        <td>Otto</td>
        <td>Otto@gmail.com</td>
      </tr>

      <tr>
        <th scope="row form-check">
          <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
        </th>
        <td>32</td>
        <td>Thornton</td>
        <td>Thornton@gmail.com</td>
      </tr>

      <tr>
        <th scope="row form-check">
          <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
        </th>
        <td>31</td>
        <td>tom</td>
        <td>Thornton@gmail.com</td>
      </tr>

      </tbody>
    </table>
  </form>
</div>

app/views/youtube/index.html.erb
<% @youtube_data.items.each do |item| %>
  <% snippet = item.snippet %>
  <p><%= snippet.title %></p>
  <p><%= snippet.published_at %><%= snippet.channel_title %></p>
  <div><iframe width="560" height="315" src="https://www.youtube.com/embed/<%= item.id.video_id %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
<% end %>